import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "700"],
  variable: "--font-poppins",
  display: "swap",
});



export const metadata: Metadata = {
  title: "E-commerce Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased font-poppins `}
      >
        {children}
        <ToastContainer/>
      </body>
    </html>
  );
}
